version: '3.8'
services:
  db:
    image: mysql:8.0.33
    container_name: couponify-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: couponify
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
