spring:
  profiles:
    active: local
  application:
    name: coupon-api
  config:
    import:
      - classpath:properties/datasource.yml
      - classpath:properties/jpa.yml

schedule:
  use: true
  cron:
    expire: "0 0 0 * * *"
    issue: "*/10 * * * * *"

cache:
  coupon:
    expiration:
      hours: 1
