spring:
  profiles:
    active: local
  application:
    name: coupon-api
  config:
    import:
      - classpath:properties/datasource.yml
      - classpath:properties/jpa.yml

schedule:
  cron: "0 0 0 * * *"
  use: true
